Repository B03-Killer/WorkConnect, pull requests merged in 2024-07, with the labels that each got.

#2 init: create next app 추가
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/launch.json
  .vscode/settings.json
  README.md
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  src/app/(providers)/(root)/page.tsx
  src/app/(providers)/layout.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/providers/QueryProvider.tsx
  src/providers/SupabaseProvider.tsx
  src/styles/globals.css
  src/types/common.ts
  src/types/supabase.ts
  src/utils/middleware.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/supabaseClient.ts
  src/utils/supabase/supabaseServer.ts
  supabase/.gitignore
  supabase/config.toml
  supabase/seed.sql
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feat

#27 (post) createChannel 응답값 수정, (post) createChannelUser 핸들러 추가
  src/api/api.ts
  src/api/channelAPi.ts
  src/api/channelUser.ts
  src/app/(providers)/(root)/video-channel/_components/VideoList/VideoList.tsx
  src/app/(providers)/(root)/video-channel/page.tsx
  src/app/api/channel-user/constants.ts
  src/app/api/channel-user/route.ts
  src/app/api/channel/route.ts
  src/constants/channel.ts
  src/hooks/useChannel.ts
  src/services/channel.ts
  src/services/channelUser.ts
  src/types/channel.ts
  src/types/channelUser.ts
  src/types/supabase.ts
Labels: ✨ Feat

#31 영상통화 기능 구현
  src/api/api.ts
  src/api/channelAPI.ts
  src/api/channelUser.ts
  src/api/todoAPI.ts
  src/api/workspaceUserAPI.ts
  src/api/workspaceUserListAPI.ts
  src/app/(providers)/(root)/video-channel/[name]/page.tsx
  src/app/(providers)/(root)/video-channel/_components/PrejoinContent/PreJoinContent.tsx
  src/app/(providers)/(root)/video-channel/_components/VideoConference/VideoConference.tsx
  src/app/(providers)/(root)/video-channel/_components/VideoList/VideoList.tsx
  src/app/(providers)/(root)/video-channel/_components/VideoRoom/VideoRoom.tsx
  src/app/(providers)/(root)/video-channel/create/page.tsx
  src/app/(providers)/(root)/video-channel/page.tsx
  src/app/api/channel-user/constants.ts
  src/app/api/channel-user/route.ts
  src/app/api/channel/route.ts
  src/app/api/workspace-userlist/route.ts
  src/hooks/useChannel.ts
  src/hooks/useChannelUser.ts
  src/hooks/useShallowSelector.ts
  src/hooks/useWorkspaceUserList.ts
  src/services/channelUser.ts
  src/services/videoChannel.ts
  src/store/streamSetStore.ts
  src/types/channel.ts
  src/types/supabase.ts
Labels: ✨ Feat

#33 feat: 채널 목록 / 채널 상세 / 채널 등록
  package-lock.json
  package.json
  src/api/api.ts
  src/api/channelAPI.ts
  src/api/chatAPI.ts
  src/api/index.ts
  src/api/workspaceAPI.ts
  src/app/(providers)/(root)/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/chat/(home)/_components/ChannelItem/index.ts
  src/app/(providers)/(root)/chat/(home)/_components/ChannelList/ChatList.tsx
  src/app/(providers)/(root)/chat/(home)/_components/ChannelList/index.ts
  src/app/(providers)/(root)/chat/(home)/_utils/updateChatChannels.ts
  src/app/(providers)/(root)/chat/(home)/page.tsx
  src/app/(providers)/(root)/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/chat/[id]/_components/Chat/index.ts
  src/app/(providers)/(root)/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/chat/[id]/_components/ChatFooter/index.ts
  src/app/(providers)/(root)/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/chat/[id]/_components/ChatMessages/index.ts
  src/app/(providers)/(root)/chat/[id]/_components/ChatMessagesWrapper/ChatMessagesWrapper.tsx
  src/app/(providers)/(root)/chat/[id]/_components/ChatMessagesWrapper/index.ts
  src/app/(providers)/(root)/chat/[id]/page.tsx
  src/app/(providers)/(root)/chat/_components/TestButton.tsx
  src/app/(providers)/(root)/chat/_components/TestHeader.tsx
  src/app/(providers)/(root)/chat/_constants/constants.ts
  src/app/(providers)/(root)/chat/_hooks/useMutationChat.tsx
  src/app/(providers)/(root)/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/chat/_utils/subscribe.ts
  src/app/(providers)/(root)/chat/add/_components/SearchResults.tsx
  src/app/(providers)/(root)/chat/add/_components/SelectedUsers.tsx
  src/app/(providers)/(root)/chat/add/_hooks/useCreateChannel.tsx
  src/app/(providers)/(root)/chat/add/_provider/SearchUsersProvider.tsx
  src/app/(providers)/(root)/chat/add/group-setting/page.tsx
  src/app/(providers)/(root)/chat/add/layout.tsx
  src/app/(providers)/(root)/chat/add/page.tsx
  src/app/api/channel/[id]/users/constants.ts
  src/app/api/channel/[id]/users/route.ts
  src/app/api/channel/existing-id/constants.ts
  src/app/api/channel/existing-id/route.ts
  src/app/api/chat/(home)/constants.ts
  src/app/api/chat/(home)/route.ts
  src/app/api/chat/[id]/constants.ts
  src/app/api/chat/[id]/route.ts
  src/app/api/workspace/[id]/users/search/constants.ts
  src/app/api/workspace/[id]/users/search/route.ts
  src/components/InfiniteScroll/InfiniteScroll.tsx
  src/components/InfiniteScroll/index.ts
  src/constants/chat.ts
  src/services/channel.ts
  src/services/chat.ts
  src/services/chatChannel.ts
  src/services/workspaceUser.ts
  src/types/channel.ts
  src/types/channelUser.ts
  src/types/chat.ts
  src/types/common.ts
  src/types/supabase.ts
  src/types/workspaceUser.ts
  src/utils/createRealtimeSubscription.ts
Labels: ✨ Feat

#45 feat: 채팅 상세 리소스 업로드 구현
  package.json
  src/app/(providers)/(root)/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/chat/[id]/_components/ChatMessagesWrapper/ChatMessagesWrapper.tsx
  src/app/(providers)/(root)/chat/[id]/_components/FileButton/FileButton.tsx
  src/app/(providers)/(root)/chat/[id]/_components/FileButton/index.ts
  src/app/(providers)/(root)/chat/[id]/_components/FileInput/FileInput.tsx
  src/app/(providers)/(root)/chat/[id]/_components/FileInput/index.ts
  src/app/(providers)/(root)/chat/[id]/_components/MessageInput/MessageInput.tsx
  src/app/(providers)/(root)/chat/[id]/_components/MessageInput/index.ts
  src/app/(providers)/(root)/chat/[id]/_components/UtilsMenus/UtilsMenus.tsx
  src/app/(providers)/(root)/chat/[id]/_components/UtilsMenus/index.ts
  src/app/(providers)/(root)/chat/[id]/page.tsx
  src/app/(providers)/(root)/chat/_components/TestHeader.tsx
  src/app/(providers)/(root)/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/chat/add/_utils/getExistingChannelId.ts
  src/app/(providers)/(root)/chat/add/page.tsx
  src/constants/chat.ts
  src/icons/image.svg
  src/icons/menu.svg
  src/icons/paperclip.svg
  src/icons/plus.svg
  src/icons/smile.svg
  src/icons/video.svg
  src/providers/QueryProvider.tsx
  src/utils/file.ts
Labels: ✨ Feat

#58 fix: get_existing_channel_id rpc 이름 변경
  src/services/channel.ts
  src/types/supabase.ts
Labels: 🐞BugFix

#61 feat: useWorkspaceId hook 추가
  src/hooks/useWorkspaceId.ts
Labels: ✨ Feat

#65 refactor: 화상채팅 목록, 추가로직 통일
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/page.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/[name]/_components/VideoRoom/VideoRoom.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/prejoin/_components/PrejoinContent/PreJoinContent.tsx
  src/types/channel.ts
  src/types/supabase.ts
Labels: 🛠️ Refactor

#73 미들웨어 추가 및 디자인 일부 수정
  src/app/(providers)/(root)/[workspaceId]/user/Logout.tsx
  src/app/(providers)/(root)/auth/_components/index.ts
  src/app/(providers)/(root)/auth/_utils/cookieUtils.ts
  src/app/(providers)/(root)/auth/login/page.tsx
  src/app/(providers)/(root)/auth/signup/page.tsx
  src/app/(providers)/(root)/auth/signup/verify/page.tsx
  src/app/(providers)/(root)/page.tsx
  src/app/(providers)/(root)/workspace/landing/page.tsx
  src/app/(providers)/(root)/workspace/new/page.tsx
  src/app/api/signup/kakao/route.ts
  src/middleware.ts
  src/styles/globals.css
  src/utils/middleware.ts
Labels: 💄 style, ✨ Feat

#75 이미지 삭제시 엑박 이미지 추가
  .prettierignore
  public/images/common/broken-file.png
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/file/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/media/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/notice/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetail/ChatDetail.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetail/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Sidebar/Sidebar.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Sidebar/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/UtilsMenus.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/index.ts
  src/icons/Hash.svg
  src/icons/image.svg
Labels: ✨ Feat

#84 공통 이미지 비디오 에러처리 & 파일 페이지 연동
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/file/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/media/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatImage/ChatImage.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatImage/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatVideo/ChatVideo.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatVideo/index.ts
  src/components/Tabs/Tabs.tsx
  src/icons/Folder.svg
  src/types/common.ts
Labels: ✨ Feat

#89 컨텍스트 메뉴 추가
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/ContextMenu/ContextMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/ContextMenu/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatVideo/ChatVideo.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/DropdownProvider.tsx
  src/app/(providers)/(root)/test/page.tsx
  src/icons/Copy.svg
  src/icons/Edit.svg
  src/icons/Trash.svg
Labels: ✨ Feat

#90 메인 병합
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/ContextMenu/ContextMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/ContextMenu/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatVideo/ChatVideo.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/DropdownProvider.tsx
  src/app/(providers)/(root)/test/page.tsx
  src/icons/Copy.svg
  src/icons/Edit.svg
  src/icons/Trash.svg
Labels: ✨ Feat
