Repository B03-Killer/WorkConnect, pull requests merged in 2024-08, with the labels that each got.

#108 채널 목록, 채널 등록, 채널 검색 UI 적용
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelList/ChatList.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelList/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/ContextMenu/ContextMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetail/ChatDetail.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetail/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessagesWrapper/ChatMessagesWrapper.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Sidebar/Sidebar.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/ContextMenuProvider.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/DropdownProvider.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SearchResults.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SelectedUsers.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/page.tsx
  src/app/(providers)/layout.tsx
  src/components/ChatCard/ChatCard.tsx
  src/components/PageLayout/PageLayout.tsx
  src/constants/channel.ts
  src/constants/chat.ts
  src/icons/Check.svg
  src/icons/MessagePlus.svg
  src/icons/index.ts
  src/providers/SnackBarContext.tsx
  src/types/channel.ts
  src/types/chat.ts
  src/types/supabase.ts
  src/types/workspaceUser.ts
  src/utils/createRealtimeSubscription.ts
Labels: ✨ Feat

#120 채팅 버그 수정
  src/api/chatAPI.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatImage/ChatImage.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatVideo/ChatVideo.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageTextarea/MessageTextarea.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Sidebar/Sidebar.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/UtilsMenus.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/ContextMenuProvider.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useMutationChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/getDmChannelName.ts
  src/app/api/channel/[id]/channel-name/constants.ts
  src/app/api/channel/[id]/channel-name/route.ts
  src/providers/SnackBarContext.tsx
  src/services/channel.ts
Labels: ✨ Feat

#132 그룹 채팅방 이미지 업로드
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ContextMenu/ContextMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ContextMenu/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useMutationChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/app/api/channel/route.ts
  src/icons/index.ts
  src/services/channel.ts
  src/types/channel.ts
Labels: ✨ Feat

#138 채팅 UI 상대방 화면 수정, 하드코딩 수정
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/UtilsMenus.tsx
Labels: 🩹 fix

#140 feat: 공지 기능, 상단 공지 노출 기능 추가
  package-lock.json
  package.json
  src/api/chatAPI.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/file/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/media/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/notice/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ContextMenu/ContextMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenu/UtilsMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenu/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_components/TestButton.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_components/TestHeader.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useMutationChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SearchResults.tsx
  src/app/api/chat/[id]/latest-notice/constants.ts
  src/app/api/chat/[id]/latest-notice/route.ts
  src/app/api/chat/[id]/route.ts
  src/components/SnackBar/SnackBar.tsx
  src/components/Typography/Typography.tsx
  src/icons/Bell.svg
  src/icons/ChevronDownIcon.svg
  src/icons/FileText.svg
  src/icons/index.ts
  src/services/chat.ts
  src/types/chat.ts
  src/types/supabase.ts
  src/utils/isEmpty.ts
Labels: ✨ Feat

#141 메인 병합
  package-lock.json
  package.json
  src/api/chatAPI.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/file/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/media/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/notice/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ContextMenu/ContextMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenu/UtilsMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenu/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_components/TestButton.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_components/TestHeader.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useMutationChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SearchResults.tsx
  src/app/api/chat/[id]/latest-notice/constants.ts
  src/app/api/chat/[id]/latest-notice/route.ts
  src/app/api/chat/[id]/route.ts
  src/components/SnackBar/SnackBar.tsx
  src/components/Typography/Typography.tsx
  src/icons/Bell.svg
  src/icons/ChevronDownIcon.svg
  src/icons/FileText.svg
  src/icons/index.ts
  src/services/chat.ts
  src/types/chat.ts
  src/types/supabase.ts
  src/utils/isEmpty.ts
Labels: ✨ Feat

#143 feat: Avatar 시스템 컴포넌트 추가
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/index.ts
  src/icons/index.ts
Labels: ✨ Feat

#144 메인 병합
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/index.ts
  src/icons/index.ts
Labels: ✨ Feat

#146 사이트 메타데이터, 파비콘 추가
  public/images/favicons/android-icon-144x144.png
  public/images/favicons/android-icon-192x192.png
  public/images/favicons/android-icon-36x36.png
  public/images/favicons/android-icon-48x48.png
  public/images/favicons/android-icon-72x72.png
  public/images/favicons/android-icon-96x96.png
  public/images/favicons/apple-icon-114x114.png
  public/images/favicons/apple-icon-120x120.png
  public/images/favicons/apple-icon-144x144.png
  public/images/favicons/apple-icon-152x152.png
  public/images/favicons/apple-icon-180x180.png
  public/images/favicons/apple-icon-57x57.png
  public/images/favicons/apple-icon-60x60.png
  public/images/favicons/apple-icon-72x72.png
  public/images/favicons/apple-icon-76x76.png
  public/images/favicons/apple-icon-precomposed.png
  public/images/favicons/apple-icon.png
  public/images/favicons/favicon-16x16.png
  public/images/favicons/favicon-32x32.png
  public/images/favicons/favicon-96x96.png
  public/images/favicons/favicon.ico
  src/app/favicon.ico
  src/app/layout.tsx
Labels: ✨ Feat

#150 style: 랜딩 스타일 수정
  src/app/(providers)/(root)/page.tsx
Labels: 💄 style

#152 feat: 애플 메타데이터 애플리케이션 설정
  src/app/layout.tsx
Labels: 📄Docs

#155 style: 아이폰 상태바 테마 변경
  src/app/layout.tsx
Labels: 💄 style

#169 fix: 프로필 페이지 변경시 한박자 늦게 변경되는 현상 수정
  src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/page.tsx
  src/hooks/useWorkspaceUser.ts
Labels: 🐞BugFix

#170 메인 병합
  src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/page.tsx
  src/hooks/useWorkspaceUser.ts
Labels: 🐞BugFix

#173 feat: 공지 등록시 리얼타임 반영
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/Loader.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/_components/Splash/Splash.tsx
  src/hooks/useLoader.tsx
  src/icons/WorkConnectLogo.svg
  src/icons/index.ts
Labels: ✨ Feat

#175 style: 체크 아이콘 변경
  package-lock.json
  package.json
  src/app/(providers)/(root)/[workspaceId]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/_components/HomeMemberCard/HomeMemberCard.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/components/TopSelect/TopSelect.tsx
  src/icons/Check1.svg
  src/icons/index.ts
  tailwind.config.ts
Labels: 💄 style

#176 메인 병합
  package-lock.json
  package.json
  src/app/(providers)/(root)/[workspaceId]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/_components/HomeMemberCard/HomeMemberCard.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/Loader.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/app/(providers)/(root)/_components/Splash/Splash.tsx
  src/components/TopSelect/TopSelect.tsx
  src/hooks/useLoader.tsx
  src/icons/Check1.svg
  src/icons/WorkConnectLogo.svg
  src/icons/index.ts
  tailwind.config.ts
Labels: ✨ Feat

#180 feat: 공지사항 삭제시에도 리얼타임 반영
  src/api/chatAPI.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SearchResults.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SelectedUsers.tsx
  src/components/Avatar/Avatar.tsx
Labels: ✨ Feat

#181 메인 병합
  src/api/chatAPI.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SearchResults.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SelectedUsers.tsx
  src/components/Avatar/Avatar.tsx
Labels: ✨ Feat

#188 채팅방 중복 생성 오류 수정
  src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
Labels: 🐞BugFix

#192 fix: 채널 목록 쿼리키 미반영 개선
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
Labels: 🐞BugFix

#194 fix: 쿼리키 리얼타임에도 반영
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
Labels: 🐞BugFix

#193 메인 병합
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/to-do-list/(providers)/(home)/page.tsx
  src/components/TopSelect/TopSelect.tsx
  src/hooks/useTodo.ts
  src/hooks/useWorkspaceList.ts
Labels: 🐞BugFix

#197 오타 수정
  src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/_components/EditOrMessageButton/EditOrMessageButton.tsx
Labels: 🐞BugFix

#178 새로 고침시 유저 이름 사라지는 오류 수정 / 통화 방 토큰이 생성이 안될 시 생기는 에러처리 개선.
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/BottomControlBar/BottomControlBar.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/VideoConference/CustomVideoConference.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/VideoRoom/VideoRoom.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/DeviceMenu/DeviceMenu.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/DeviceMenuButton/DeviceMenuButton.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/PrejoinContent/PreJoinContent.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/page.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/_components/NoneList/NoneList.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/_components/NoneList/index.ts
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/_components/VideoList/VideoList.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/_components/VideoList/index.ts
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/_components/VideoListItem/VideoListItem.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/_components/VideoListItem/index.ts
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/create/_components/UserItem/UserItem.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/create/_components/UserItem/index.ts
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/create/page.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(sub)/layout.tsx
Labels: 🩹 fix

#220 feat: bottom nav 마이페이지 메뉴 삭제
  src/components/BottomNavigationBar/BottomNavigationBar.tsx
Labels: ✨ Feat

#222 feat: 하단바 마이페이지 메뉴 제거
  src/components/BottomNavigationBar/BottomNavigationBar.tsx
Labels: ✨ Feat

#230 style: 채팅 상세 리팩터링
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/ChatDetailLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessagesWrapper/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chats/Chats.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chats/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageSender/MessageSender.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageSender/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageTextarea/MessageTextarea.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Messages/Messages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Messages/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessagesContainer/MessageWrapper.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessagesContainer/MessagesContainer.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessagesContainer/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Sidebar/Sidebar.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/ContextMenuProvider.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useGetChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/AddChatLayout/AddChatLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/AddChatLayout/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/layout.tsx
  src/app/(providers)/layout.tsx
  src/components/TopBar/TopBar.tsx
  src/providers/AuthProvider.tsx
Labels: 🛠️ Refactor

#238 refactor: 채팅 리스트 리팩터링
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChannelHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/ChatDetailLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chats/Chats.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Messages/Messages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_hook/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_hook/useGetChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/Loader.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useGetChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/getChannelName.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
Labels: 🛠️ Refactor

#240 메인 병합
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChannelHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/ChatDetailLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessagesWrapper/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chats/Chats.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chats/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageSender/MessageSender.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageSender/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessageTextarea/MessageTextarea.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Messages/Messages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Messages/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessagesContainer/MessageWrapper.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessagesContainer/MessagesContainer.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/MessagesContainer/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Sidebar/Sidebar.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_hook/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_hook/useGetChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_provider/ContextMenuProvider.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/Loader.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_component/Loader/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/getChannelName.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/AddChatLayout/AddChatLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/_components/AddChatLayout/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/add/layout.tsx
  src/app/(providers)/layout.tsx
  src/components/TopBar/TopBar.tsx
  src/providers/AuthProvider.tsx
Labels: 🛠️ Refactor

#244 fix: 리팩터링 후 채널명이 보이지 않는 현상 수정
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/ChatDetailLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/_hook/useGetChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_utils/getChannelName.ts
  src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
Labels: 🐞BugFix

#246 api 응답 status 설정
  src/app/api/channel-user/route.ts
  src/app/api/channel/[id]/users/constants.ts
  src/app/api/channel/[id]/users/route.ts
  src/app/api/channel/existing-id/constants.ts
  src/app/api/channel/existing-id/route.ts
  src/app/api/chat/(home)/constants.ts
  src/app/api/chat/(home)/route.ts
  src/app/api/chat/[id]/constants.ts
  src/app/api/chat/[id]/latest-notice/constants.ts
  src/app/api/chat/[id]/latest-notice/route.ts
  src/app/api/chat/[id]/route.ts
  src/app/api/workspace/[id]/users/search/constants.ts
  src/app/api/workspace/[id]/users/search/route.ts
  src/services/chat.ts
Labels: 🛠️ Refactor

#249 미들웨어 리팩터링
  src/app/(providers)/(root)/auth/login/page.tsx
  src/app/(providers)/(root)/workspace/landing/page.tsx
  src/app/(providers)/(root)/workspace/new/page.tsx
  src/app/(providers)/layout.tsx
  src/components/TopSelect/TopSelect.tsx
  src/constants/redirectRoutes.ts
  src/middleware.ts
  src/utils/cookieUtils.ts
  src/utils/supabase/getCurrentRoute.ts
  src/utils/supabase/middleware.ts
  src/utils/workspaceCookie.ts
Labels: 🐞BugFix

#256 회원가입 단계에서 초대코드 입력 페이지시 undefined로 리다이렉트 되는 오류 수정
  src/constants/redirectRoutes.ts
  src/utils/supabase/middleware.ts
Labels: 🐞BugFix

#258 유저 채팅 확인 여부 기능 추가
  src/api/channelAPI.ts
  src/api/chatAPI.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/Chat/Chat.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/Chat/Components.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/Chats/Chats.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/Chats/Components.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/MessageTextarea/MessageTextarea.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/Messages/Messages.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/UpdateChannelReadAt/UpdateChannelReadAt.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_components/UpdateChannelReadAt/index.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_hooks/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_hooks/useFetchChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_utils/getLastActiveAtForChannel.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/_utils/subscribe.ts
  src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/chat/_hook/useChatMutation.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hook/useChatQuery.tsx
  src/app/(providers)/(root)/[workspaceId]/chat/_hook/useGetChannelId.ts
  src/app/api/channel/[id]/update-active-at/constants.ts
  src/app/api/channel/[id]/update-active-at/route.ts
  src/services/channel.ts
  src/types/channel.ts
  src/types/supabase.ts
Labels: ✨ Feat

#250 Sentry 모니터링 추가
  .gitignore
  README.md
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/instrumentation.ts
  src/utils/supabase/middleware.ts
Labels: ✨ Feat

#274 pc 일때 하단바 영역 제거
  src/components/PageLayout/PageLayout.tsx
Labels: 💄 style

#296 style: 모바일 헤더 스타일 수정
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatDetailLayout/ChatDetailLayout.tsx
Labels: 💄 style

#307 채널 api 정리 및 채널 목록 아이디 조회 api 추가
  src/api/channelAPI.ts
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/Chats/Chats.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/MessageTextarea/MessageTextarea.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/Messages/Messages.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/UpdateChannelReadAt/UpdateChannelReadAt.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_hooks/useFetchChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_hook/useGetParamsChannelId.ts
  src/app/(providers)/(root)/[workspaceId]/channels/(home)/layout.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_hooks/useRedirectForPC.ts
  src/app/(providers)/(root)/[workspaceId]/channels/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SearchInput/SearchInput.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SearchMemberCard/SearchMemberCard.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SelectedUsers/SelectedUsers.tsx
  src/app/api/channel/(home)/route.ts
  src/app/api/channel/id/constants.ts
  src/app/api/channel/id/route.ts
  src/app/api/channels/(home)/constants.ts
  src/app/api/channels/(home)/route.ts
  src/components/BottomNavigationBar/BottomNavigationBar.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/middleware.ts
  src/services/channel.ts
  src/types/supabase.ts
  src/utils/middleware.ts
  src/utils/middleware/getCurrentRoute.ts
  src/utils/middleware/handleAuthRedirect.ts
  src/utils/middleware/redirectToChannel.ts
  src/utils/middleware/supabaseMiddleware.ts
  src/utils/supabase/middleware.ts
Labels: ✨ Feat

#309 fix: 채팅 메세지에 stale time이 있어서 데이터가 바로 반영되지 않는 현상 수정
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_hook/useChatQuery.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_utils/getQueryOptions.ts
  src/app/(providers)/(root)/[workspaceId]/channels/_utils/getQueryOptions.ts
  src/providers/QueryProvider.tsx
Labels: 🩹 fix

#311 안 읽은 채팅 목록에서 보여지기 (realtime 미적용)
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/Chats/Components.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
  src/components/ChatCard/ChatCard.tsx
  src/types/channel.ts
  src/types/supabase.ts
Labels: ✨ Feat

#313 공지방 노출시 채널 목록에 노출되도록 개선
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatDetailLayout/ChatDetailLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_hooks/useChannelHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/_components/EditOrMessageButton/EditOrMessageButton.tsx
  src/components/Layout/PageLayout/PageLayout.tsx
  src/services/channel.ts
  src/types/channel.ts
  src/types/supabase.ts
Labels: ✨ Feat

#319 realtime cleanup 미작동 오류 수정 / 채팅 수신시 채널 활동시간 업데이트
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatNotice/ChatNotice.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/Messages/Messages.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_hooks/useChatHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_utils/subscribe.ts
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_hooks/useChannelHandlers.ts
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_utils/subscribe.ts
  src/utils/createRealtimeChannel.ts
Labels: 🐞BugFix, ✨ Feat

#322 채널 목록 realtime eq 수정
  src/api/channelAPI.ts
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatDetailLayout/ChatDetailLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_hooks/useFetchChannelName.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_constants/constants.ts
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_hook/useChatQuery.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_utils/getQueryOptions.ts
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelItem/ChannelItem.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_utils/subscribe.ts
  src/app/api/channel/[id]/info/constants.ts
  src/app/api/channel/[id]/info/route.ts
  src/providers/SnackBarContext.tsx
  src/services/channel.ts
  src/types/supabase.ts
Labels: ✨ Feat

#325 style: 채팅 추가 검색 페이지 pc 스타일 반영
  src/app/(providers)/(root)/[workspaceId]/channels/add/(home)/page.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/_components/AddChannelLayout/AddChannelLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SearchMemberCard/SearchMemberCard.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SelectedUsers/SelectedUsers.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/group-setting/_components/GroupNameInput/GroupNameInput.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/add/group-setting/page.tsx
Labels: 💄 style

#328 상태메세지 아이콘 추가
  src/assets/userStatusList.ts
Labels: 💄 style

#315 style: UX Writing 통일
  src/app/(providers)/(root)/[workspaceId]/_components/InviteCodeButton/InviteCodeButton.tsx
  src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/edit/page.tsx
  src/app/(providers)/(root)/auth/signup/page.tsx
  src/app/(providers)/(root)/workspace/new/page.tsx
Labels: 💄 style

#340 channel pc 디자인 변경 / 채팅 mobile 헤더 변경
  src/app/(providers)/(root)/[workspaceId]/channels/(home)/layout.tsx
  src/components/Layout/PageLayout/PageLayout.tsx
  src/components/Layout/SelectHeader/SelectHeader.tsx
  src/components/Layout/TopBar/TopBar.tsx
Labels: 💄 style

#353 글씨 크기 안맞는 부분 수정
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/RenderTrack/RenderTrack.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/CustomPrejoin/CustomPrejoin.tsx
Labels: 💄 style

#357 feat: 채팅 로딩 추가
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/loading.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/(home)/loading.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
  src/app/(providers)/(root)/[workspaceId]/channels/_components/TopBarButtons/TopBarButtons.tsx
  src/app/loading.tsx
  src/hooks/useWorkspaceId.ts
Labels: ✨ Feat

#360 feat: delete id 센트리 디버그
  src/services/chat.ts
Labels: ✨ Feat

#361 메인 병합
  src/services/chat.ts
Labels: 🐞BugFix

#364 feat: 프로덕션 메세지 삭제 로그 추가
  src/services/chat.ts
Labels: 🐞BugFix

#365 메인병합
  src/services/chat.ts
Labels: 🐞BugFix

#368 context menu 간격 수정
  src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_provider/ContextMenuProvider.tsx
Labels: 💄 style

#362 fix/화상채팅 포커싱 화면 수정.
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/FocusedVideoTrack/FocusedVideoTrack.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/RenderTrack/RenderTrack.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/VideoConference/CustomVideoConference.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/WebLayout/WebLayout.tsx
  src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_store/useFocusTrack.ts
Labels: 🩹 fix

#377 github actions 개인 레포를 연결하여 배포 자동화 추가
  .github/workflows/deploy.yml
  .gitignore
  build.sh
Labels: ✨ Feat

#378 메인 병합
  .github/workflows/deploy.yml
  .gitignore
  build.sh
Labels: ✨ Feat

#380 아이콘 대소문자 파일 오류 수정
  src/icons/Menu.svg
  src/icons/index.ts
Labels: 🩹 fix
